### ISSUE TITLE
Appending files is not working after `formdata-node@4.4.1`

### ISSUE THREAD

**Issue by DanielRamosAcosta** [octet-stream/form-data-encoder#14]
Hello! I'm getting a weird error when trying to add files to a form.

I've created a library similar to supertest called [tepper](https://github.com/DanielRamosAcosta/tepper), and the other day the bot tried to upgrade `formdata-node` from `4.3.2` to `4.4.1`. The CI of [the PR](https://github.com/DanielRamosAcosta/tepper/pulls) was failing, and I've been trying to narrow up the error.

Finally, I've managed to reproduce the error in this separate repository: [DanielRamosAcosta/form-data-issue](https://github.com/DanielRamosAcosta/form-data-issue). The CI is passing on the main branch, but it is failing after upgrade, as you can see in [this PR](https://github.com/DanielRamosAcosta/form-data-issue/pull/1).

Output at `4.3.2`:

```
--form-data-boundary-xxxxxxxxxxxxxxxx
Content-Disposition: form-data; name="stream"; filename="file.txt"
Content-Type: text/plain

Stream content
--form-data-boundary-xxxxxxxxxxxxxxxx--
```

Output at `4.4.1`

```
--form-data-boundary-xxxxxxxxxxxxxxxx
Content-Disposition: form-data; name="stream"

[object File]
--form-data-boundary-xxxxxxxxxxxxxxxx--
```

There seems to be a problem with the `File` detection at `4.4.1`! No more time today, but I could give a try reproducing the error at this repo and providing a fix.

**Comment by octet-stream** [comment]
Well, I should've read GitHub warnings more carefully. Hope at least you got my answer via email.

**Comment by octet-stream** [comment]
The issue happens because in `1.x` I was more strict when testing file-ish objects:
https://github.com/octet-stream/form-data-encoder/blob/111c7e53d7746b0dfb7c99fcda96b81cca282d82/lib/util/isFileLike.ts#L37-L39

If you're able to upgrade form-data-encoder to `2.x`, this should solve your problem.

**Comment by octet-stream** [comment]
The fix is released under https://github.com/octet-stream/form-data-encoder/releases/tag/v1.8.0

Hope this will help.

Please, consider switch over `2.x`, I am not going to support `1.x` any further.

**Comment by octet-stream** [comment]
@jimmywarting That's a great news! However your comment is off-topic since the issue does not seem to be related to blob backed up by fs. But thank you anyway for pointing this up.

**Comment by DanielRamosAcosta** [comment]
Thanks @octet-stream, after upgrading to [form-data-encoder to `1.8.0`](https://github.com/DanielRamosAcosta/form-data-issue/pull/1) everything is working now. Will try to upgrade to `2.x` shortly, thanks!

**Comment by DanielRamosAcosta** [comment]
Just one more question @octet-stream. Version `2.x` dropped CommonJs, however, from tepper I need to support CommonJS clients. I think that I need to stick with `1.8`, do you see another solution?

**Comment by jimmywarting** [comment]
you can use dynamic import in cjs projects

```js
import(pkg).then(...)
```

**Comment by octet-stream** [comment]
Yes, this should work. I also saw somebody making cjs version of popular packages, can't remember how those called... But you can find cjs version for latest versions of both `formdata-node` and `form-data-encoder`

**Comment by octet-stream** [comment]
>  I also saw somebody making cjs version of popular packages, can't remember how those called

@DanielRamosAcosta found it: https://github.com/esm2cjs/form-data-encoder
Maybe this will help if you still need cjs support in v2.
