### ISSUE TITLE
Breaking change in 1.8.0

### ISSUE THREAD

**Issue by ericmorand** [octet-stream/form-data-encoder#15]
The following change is a breaking change:

https://github.com/octet-stream/form-data-encoder/blame/v1.8.0/lib/FormDataEncoder.ts#L77

It is possible that some other changes brought by this _minor_ update are also breaking changes.

**Comment by ericmorand** [comment]
The commit message is "fix linting issue". There is no mention about a bug fix. Instead it looks like a cosmetic change. Except of the commit message is misleading.

**Comment by octet-stream** [comment]
Ah, right, I see now. The release however mentions the change, so it was intentional: https://github.com/octet-stream/form-data-encoder/releases/tag/v1.8.0 the "Backport headers changes"

**Comment by octet-stream** [comment]
Okay, I can revert this.

**Comment by ericmorand** [comment]
Thanks. We have fixed the version to 1.7.2. in our own projects, for now - we have a critical product that requires to be built tonight. But it may not be as easy for some other teams. 🙂

**Comment by octet-stream** [comment]
Sorry I broke your product. The https://github.com/octet-stream/form-data-encoder/releases/tag/v1.9.0 should revert these changes. 1.8.0 will be marked as deprecated. Thanks for reaching me out!

**Comment by octet-stream** [comment]
Also please consider upgrade to `v2` when it is possible, the `1.x` will no longer receive updates (except for those things I might broke in 1.8.0)

**Comment by ericmorand** [comment]
Thank you so much.

We plan on moving to v2. For now our build toolchain doesn't emit an ESM artifact but we will change this in the next few weeks - to be able to benefit of the most recent version of your fantastic package, and some others that are also moving to ESM-only.

Again, thanks. Much appreciated.

**Comment by octet-stream** [comment]
I'm gonna close this, hope your issue is resolved.
