### ISSUE TITLE
Type error using Node.js global `FormData` instance with `FormDataEncoder` constructor

### ISSUE THREAD

**Issue by jaydenseric** [octet-stream/form-data-encoder#16]
This part of the type `FormDataLike`:

https://github.com/octet-stream/form-data-encoder/blob/f76123116b61a71ef4db65bade66bc45e24e8486/src/FormDataLike.ts#L45

Is causing this error when you attempt to use a Node.js global `FormData` instance with the `FormDataEncoder` constructor:

> Argument of type 'FormData' is not assignable to parameter of type 'FormDataLike'.
  Property '[Symbol.toStringTag]' is missing in type 'FormData' but required in type 'FormDataLike'.

<img width="769" alt="Screenshot 2023-08-10 at 12 40 17 pm" src="https://github.com/octet-stream/form-data-encoder/assets/1754873/8d192e8c-91e5-456f-b61f-2dfcd498709d">

**Comment by octet-stream** [comment]
I made `Symbol.toStringTag` getter optional on both `FormDataLike` and `FileLike`, and added compatibility tests for typings. This change will be released with next package update.

**Comment by octet-stream** [comment]
This fix is available since https://github.com/octet-stream/form-data-encoder/releases/tag/v4.0.0

Hope this helps.
