### ISSUE TITLE
`FormDataLike` iterator type is incorrect

### ISSUE THREAD

**Issue by Ethan-Arrowood** [octet-stream/form-data-encoder#19]
The iterator type for FormDataLike is incorrect / too restrictive (https://github.com/octet-stream/form-data-encoder/blob/8c8085d46134f0b4c2df2057cdc0d4dc085d1243/src/FormDataLike.ts#L43). It uses `Generator` which makes methods `throw` and `return` required. But based on the spec, those two are optional for iterators (see here in MDN docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#throwexception) which are linked to in the source of `FormDataLike` itself. 

I believe the types in undici are more accurate (https://github.com/nodejs/undici/blob/8050ec0224a51d44f776364820e6a16112fb4781/types/formdata.d.ts#L105 and https://github.com/nodejs/undici/blob/8050ec0224a51d44f776364820e6a16112fb4781/types/fetch.d.ts#L41-L47). 

This is actually how I found this issue. I was trying to use the FormData object from Undici with the FormDataEncoder from this library.

**Comment by octet-stream** [comment]
Hi, thanks for your feedback. Yeah, this makes sense. TypeScript itself seem to use `IterableIterator<T>` for this method (see: https://github.com/microsoft/TypeScript/blob/d9d027d0c4f5044631a0c078166b8d01f41d28b5/src/lib/dom.iterable.generated.d.ts#L98). I was a little confused by the differences between `Generator<T, TReturn, TNext>`, `Iterator<T>` and `IterableIterator<T>` types. Though, I have no idea why undici needs their own typing for this.

**Comment by Ethan-Arrowood** [comment]
That's a good point. Not sure either. But I think switching to `IterableIterator<T>` will be good change nonetheless.

**Comment by octet-stream** [comment]
Fix released with https://github.com/octet-stream/form-data-encoder/releases/tag/v3.0.1

**Comment by Ethan-Arrowood** [comment]
Incredible, thank you very much!
