### ISSUE TITLE
error TS2304: Cannot find name 'ReadableStream'

### ISSUE THREAD

**Issue by robogeek** [octet-stream/form-data-encoder#24]
Compiling form-data-encoder@4.0.2 using TypeScript 5.3.3 on Node.js 20.x, I get the following error:

```
node_modules/form-data-encoder/lib/index.d.ts:30:15 - error TS2304: Cannot find name 'ReadableStream'.

30     stream(): ReadableStream<Uint8Array> | AsyncIterable<Uint8Array>;
                 ~~~~~~~~~~~~~~
```

My application is not using this package directly.  Instead, it is referred from Got 14.0.0.

**Comment by octet-stream** [comment]
Hi. Thanks for your feedback. Can I get minimal repro w/ `tsconfig.json`?

**Comment by robogeek** [comment]
Okay... minimal reproduction is an index.ts with zero active code, and the error is generated upon compilation.

`package.json`

```json
{
  "name": "tt",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^20.10.6",
    "typescript": "^5.3.3"
  },
  "dependencies": {
    "got": "^14.0.0"
  }
}
```

`tsconfig.json`

```json
{
    "include": [ 
        "src/**/*.ts", "src/**/*.js", "src/**/*.mjs",
        "src/**/*.yml"
    ],
    "compilerOptions": {
        "lib": [ "es6", "es2022", "esnext" ],
        "target": "es2022",
        "module": "nodenext",
        "moduleResolution": "nodenext",
        "strict": true,
        "outDir": "./dist",
        "allowJs": true,
        "resolveJsonModule": true,
        "declaration": true,
        "declarationMap": true,
        "inlineSourceMap": true,
        "inlineSources": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "esModuleInterop": true
    }
}
```

`src/index.ts`

```js
import { promises as fsp } from 'node:fs';

import got from 'got';
```


Compilation:

```
$ npx tsc
node_modules/form-data-encoder/lib/index.d.ts:30:15 - error TS2304: Cannot find name 'ReadableStream'.

30     stream(): ReadableStream<Uint8Array> | AsyncIterable<Uint8Array>;
                 ~~~~~~~~~~~~~~


Found 1 error in node_modules/form-data-encoder/lib/index.d.ts:30
```

**Comment by octet-stream** [comment]
This happens because `ReadableStream` is not exposed in TypeScript by default, and probably in `@types/node` for some reason. You need to either enable `skipLibCheck` option or add `dom` to your `libs` array.
This package is not Node.js specific, so I don't think I can rely on `node:streams/web` module typings from `@types/node`.

**Comment by robogeek** [comment]
Thank you for the reply.  The change I made in `tsconfig.json` was:

```
        "lib": [ "es6", "es2022", "esnext", "dom" ],
```

And, indeed, the error went away.

**Comment by octet-stream** [comment]
Got same issue reported in my other repository. Here's more detailed explanation on the subject: https://github.com/octet-stream/form-data/issues/80

I'm now closing this issue as it's not related to my library, but rather a configuration problem.

**Comment by voxpelli** [comment]
Suggested a fix over in https://github.com/octet-stream/form-data-encoder/pull/29, feedback appreciated 🙏

**Comment by LinusU** [comment]
This was fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70269

**Comment by voxpelli** [comment]
Great! Thanks for reconnecting about it here @LinusU!
