### ISSUE TITLE
This is invalid encoder. It will not work for NodeJS

### ISSUE THREAD

**Issue by Bx1** [octet-stream/form-data-encoder#31]
This encoder uses invalid output format which doesn't work with Node.JS (when receiver is another NodeJS server). Even "native" fetch Node.JS implementation differs in output format for `multipart/form-data` from this library. Check out official requirements for `multipart/form-data`.

**Comment by octet-stream** [comment]
Can you elaborate on what's broken or implemented incorrectly?
