### ISSUE TITLE
Lookbehind Regexp for normalizeValue method doesn't work on Safari

### ISSUE THREAD

**Issue by gardun0** [octet-stream/form-data-encoder#5]
Hi,

I recently used your library on my web platform, but i've encountered an error for my Apple users, where the Lookbehind used on the regexp

https://github.com/octet-stream/form-data-encoder/blob/fa9acd75efd40ab839b340198322076aacb44f27/lib/util/normalizeValue.ts#L11

is not currently supported by Apple devices.

**Comment by octet-stream** [comment]
Hi! Thanks for bringing up this issue. I will take a look at this at the weekend, sorry.
If there's any polyfill for this, you can try and use it. Maybe Babel or core-js can do the trick. For now.

**Comment by gardun0** [comment]
Thank you so much!

I could not find any polyfill, I've found something like [this](https://www.npmjs.com/package/babel-plugin-transform-modern-regexp) but it does not have look behind assertion included.

Looking forward for a fix!

**Comment by octet-stream** [comment]
It appears I can replace negative lookbehind with replacer function. Seem to work just fine, but I am a not what performance will be comparing to the previous approach.

**Comment by octet-stream** [comment]
This fix got released in https://github.com/octet-stream/form-data-encoder/releases/tag/v1.7.2

**Comment by octet-stream** [comment]
I hope your problem is solved.
