### ISSUE TITLE
Minimum required Node.js version

### ISSUE THREAD

**Issue by jaydenseric** [octet-stream/form-data-encoder#7]
In v2 the minimum required Node.js version is [v14.18.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.18.0):

https://github.com/octet-stream/form-data-encoder/blob/4975e933e34ceb3005153cba3fd53be3e494c71f/package.json#L8-L10

Is that necessary, or can it be lowered to v14.17.0? The reason I ask is because I’ve been rolling that out as the minimum for my packages and in particular would rather not increase this for the upcoming `graphql-upload` major version:

https://github.com/jaydenseric/graphql-upload/blob/6da4fb2cdf8e4610a251babb5632bf9b97ce9f71/package.json#L47-L49

I think a lot of packages in the ecosystem will settle on Node.js v14.17.0 as the minimum to support, including it looks like `node-fetch` v4: https://github.com/node-fetch/node-fetch/issues/1452 .

**Comment by octet-stream** [comment]
I think I can lower it. The tests seem to pass on 14.17.
The problem was just that I can't run pnpm under Node 14.17, but it seem to be totally unnecessary, because I don't use it outside of my machine except for CI, but it runs on 14.x, 16.x and 18.x. Which means GitHub will use latest version of each.

**Comment by jaydenseric** [comment]
Thanks! I'll update now :)

**Comment by octet-stream** [comment]
Ah, I just remembered: I was trying to add some test for Node.js Blob in my [`formdata-node`](https://github.com/octet-stream/form-data) package, but it was added in 14.18. So I also considered that and set minimal version to 14.18 for this package too. But these test aren't essential, so I will just remove them and adjust minimal version in formdata-node too.
